from __future__ import annotations

from html import escape

from app.pipeline.models import PipelineResult, ProcessedJob


class DigestRenderer:
    """Render a PipelineResult into email-friendly HTML and plain text."""

    def render_html(self, result: PipelineResult) -> str:
        """Render the pipeline result as an HTML email body."""
        sections: list[str] = [
            "<!DOCTYPE html>",
            "<html>",
            "<head>",
            '<meta charset="utf-8">',
            "<title>MaukaKhoj Job Digest</title>",
            "</head>",
            "<body>",
            "<h1>MaukaKhoj Job Digest</h1>",
        ]

        if not result.processed_jobs:
            sections.append("<p>No matching jobs were found.</p>")
        else:
            sections.append(
                f"<p>{len(result.processed_jobs)} matching job(s) found.</p>"
            )

            for processed_job in result.processed_jobs:
                sections.append(self._render_job_html(processed_job))

        if result.source_failures:
            sections.append("<h2>Source Failures</h2>")
            sections.append("<ul>")

            for failure in result.source_failures:
                sections.append(
                    "<li>"
                    f"<strong>{escape(failure.source)}</strong>: "
                    f"{escape(failure.error)}"
                    "</li>"
                )

            sections.append("</ul>")

        sections.extend(
            [
                "<hr>",
                "<p>Generated by MaukaKhoj.</p>",
                "</body>",
                "</html>",
            ]
        )

        return "\n".join(sections)

    def render_text(self, result: PipelineResult) -> str:
        """Render the pipeline result as plain text."""
        lines = [
            "MaukaKhoj Job Digest",
            "=" * 22,
            "",
        ]

        if not result.processed_jobs:
            lines.append("No matching jobs were found.")
        else:
            lines.append(f"{len(result.processed_jobs)} matching job(s) found.")
            lines.append("")

            for processed_job in result.processed_jobs:
                lines.extend(self._render_job_text(processed_job))
                lines.append("")

        if result.source_failures:
            lines.extend(
                [
                    "Source Failures",
                    "---------------",
                ]
            )

            for failure in result.source_failures:
                lines.append(f"- {failure.source}: {failure.error}")

            lines.append("")

        lines.append("Generated by MaukaKhoj.")

        return "\n".join(lines)

    def _render_job_html(self, processed_job: ProcessedJob) -> str:
        job = processed_job.job
        score = processed_job.job_score
        explanation = processed_job.explanation

        location = escape(job.location or "Not specified")
        remote_type = escape(job.remote_type.value)
        posted_at = self._format_datetime(job.posted_at)

        sections = [
            '<article style="margin-bottom: 24px;">',
            f"<h2>#{processed_job.rank} — {escape(job.title)}</h2>",
            f"<p><strong>Company:</strong> {escape(job.company)}</p>",
            f"<p><strong>Location:</strong> {location}</p>",
            f"<p><strong>Remote:</strong> {remote_type}</p>",
            f"<p><strong>Match Score:</strong> {score.total:.2f}/100</p>",
            f"<p><strong>Posted:</strong> {escape(posted_at)}</p>",
        ]

        if job.application_url:
            sections.append(
                '<p><a href="'
                f"{escape(str(job.application_url), quote=True)}"
                '">Apply for this position</a></p>'
            )

        sections.append("<h3>Why it matches</h3>")
        sections.append("<ul>")

        for dimension in explanation.dimensions:
            status = escape(dimension.status)
            dimension_name = escape(dimension.dimension)

            sections.append(f"<li><strong>{dimension_name}:</strong> {status}")

            if dimension.reasons:
                sections.append("<ul>")

                for reason in dimension.reasons:
                    sections.append(f"<li>{escape(reason)}</li>")

                sections.append("</ul>")

            sections.append("</li>")

        sections.append("</ul>")
        sections.append("</article>")

        return "\n".join(sections)

    def _render_job_text(self, processed_job: ProcessedJob) -> list[str]:
        job = processed_job.job
        score = processed_job.job_score
        explanation = processed_job.explanation

        lines = [
            f"#{processed_job.rank} — {job.title}",
            f"Company: {job.company}",
            f"Location: {job.location or 'Not specified'}",
            f"Remote: {job.remote_type.value}",
            f"Match Score: {score.total:.2f}/100",
            f"Posted: {self._format_datetime(job.posted_at)}",
            f"Apply: {job.application_url}",
            "",
            "Why it matches:",
        ]

        for dimension in explanation.dimensions:
            lines.append(f"- {dimension.dimension}: {dimension.status}")

            for reason in dimension.reasons:
                lines.append(f"  - {reason}")

        return lines

    @staticmethod
    def _format_datetime(value) -> str:
        """Format an optional datetime for email output."""
        if value is None:
            return "Not specified"

        return value.strftime("%Y-%m-%d %H:%M UTC")
